name: HW21 Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - HW21

jobs:
  hw21:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run HW21 tests
        run: npx playwright test --grep HW21
